import { create, getAll, get, update } from "../controllers/threat.controller";
import express from "express";
import { getDetailedThreatInfo, getSuggestedFixes } from "../controllers/threatModeling.controller";
const threatRoute = express.Router();
threatRoute.get("/", getAll);
threatRoute.get("/:id", get);
threatRoute.post("/", create);
threatRoute.patch("/:id", update);
threatRoute.get("/:id/model_details", getDetailedThreatInfo);
threatRoute.get("/:id/model_suggest", getSuggestedFixes);
export default threatRoute;
